- name: install Docker
  hosts: web
  become: true

  tasks:
    - name: Update
      apt:
        update_cache: yes
    - name: Установка зависимостей
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Добавление ключа GPG для официального репозитория Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление официального репозитория Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Установка Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin # delete if not need compose
        state: present
    
    - name: Add sim-link for compose
      shell: ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
